# Generated by Django 4.1.5 on 2023-01-29 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('abbreviation', models.CharField(max_length=200, verbose_name='Abbreviation')),
                ('desc', models.TextField(max_length=2000, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Alignment',
                'verbose_name_plural': 'Alignments',
            },
        ),
        migrations.CreateModel(
            name='CharClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Class name', max_length=200, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('type', models.CharField(max_length=200, verbose_name='Type')),
                ('script', models.CharField(max_length=200, verbose_name='Script')),
                ('desc', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('desc', models.TextField(max_length=1000, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.CreateModel(
            name='Subclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Class name', max_length=200, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Subclass',
                'verbose_name_plural': 'Subclasses',
            },
        ),
        migrations.CreateModel(
            name='Subrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Subrace name', max_length=200, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Subrace',
                'verbose_name_plural': 'Subraces',
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Race name', max_length=200, verbose_name='Name')),
                ('speed', models.IntegerField(verbose_name='Base speed')),
                ('size', models.CharField(help_text='Usual size of the race', max_length=200, verbose_name='Size')),
                ('languages', models.ManyToManyField(help_text='Languages that this race knows', to='dnd.languages')),
                ('subrace', models.ManyToManyField(blank=True, to='dnd.subrace')),
            ],
            options={
                'verbose_name': 'Race',
                'verbose_name_plural': 'Races',
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Characters name', max_length=200, null=True, verbose_name='Name')),
                ('last_name', models.CharField(help_text='Characters last name', max_length=200, null=True, verbose_name='Last Name')),
                ('personality', models.TextField(help_text='Characters personality', max_length=3000, null=True, verbose_name='Personality')),
                ('appearance', models.TextField(help_text='Characters appearance', max_length=3000, null=True, verbose_name='Appearance')),
                ('backstory', models.TextField(help_text='Characters backstory', max_length=3000, null=True, verbose_name='Backstory')),
                ('alignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dnd.alignments')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('race', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dnd.race')),
                ('subrace', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dnd.subrace')),
            ],
            options={
                'verbose_name': 'Character',
                'verbose_name_plural': 'Characters',
            },
        ),
        migrations.CreateModel(
            name='AbilityScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('desc', models.TextField(max_length=2000, verbose_name='Description')),
                ('skills', models.ManyToManyField(help_text='Choose the skills that need this ability score', to='dnd.skills')),
            ],
            options={
                'verbose_name': 'Ability Score',
                'verbose_name_plural': 'Ability Scores',
            },
        ),
    ]
