# Generated by Django 4.1.5 on 2023-01-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='ability_scores',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='ability_scores',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='other_traits',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='subrace',
            name='ability_scores',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='subrace',
            name='other_traits',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
