# Generated by Django 4.1.5 on 2023-01-29 16:30

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0002_character_ability_scores_race_ability_scores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charclass',
            name='description',
            field=tinymce.models.HTMLField(help_text='Class description', max_length=3000, null=True, verbose_name='Class description'),
        ),
        migrations.AddField(
            model_name='race',
            name='description',
            field=tinymce.models.HTMLField(help_text='Race description', max_length=10000, null=True, verbose_name='Race description'),
        ),
        migrations.AddField(
            model_name='subclass',
            name='description',
            field=tinymce.models.HTMLField(help_text='Class description', max_length=3000, null=True, verbose_name='Class description'),
        ),
        migrations.AddField(
            model_name='subrace',
            name='description',
            field=tinymce.models.HTMLField(blank=True, help_text='Subrace description', max_length=3000, null=True, verbose_name='Subrace description'),
        ),
    ]
