# Generated by Django 4.1.5 on 2023-01-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0005_alter_racetraits_description_alter_racetraits_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subrace',
            name='other_traits',
        ),
        migrations.AddField(
            model_name='subrace',
            name='other_traits',
            field=models.ManyToManyField(to='dnd.racetraits'),
        ),
    ]
