# Generated by Django 4.1.5 on 2023-01-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0007_alter_subrace_ability_scores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Monsters name', max_length=200, null=True, verbose_name='Name')),
                ('size', models.CharField(blank=True, help_text='Monsters size', max_length=200, null=True, verbose_name='Size')),
                ('type', models.CharField(blank=True, help_text='Monsters type', max_length=200, null=True, verbose_name='Type')),
                ('alignment', models.CharField(blank=True, help_text='Monsters type', max_length=200, null=True, verbose_name='Alignment')),
                ('armor_class', models.IntegerField(blank=True, help_text='Monsters Armor Class', max_length=200, null=True, verbose_name='Armor Class')),
                ('hit_points', models.IntegerField(blank=True, help_text='Monsters Hit points', max_length=200, null=True, verbose_name='Hit Points')),
                ('speed', models.JSONField(blank=True, null=True, verbose_name='Speed')),
                ('ability_scores', models.JSONField(blank=True, null=True, verbose_name='Ability Scores')),
                ('skills', models.JSONField(blank=True, null=True, verbose_name='Skills')),
                ('senses', models.CharField(blank=True, help_text='Monsters senses', max_length=200, null=True, verbose_name='Senses')),
                ('languages', models.CharField(blank=True, help_text='Monsters language', max_length=200, null=True, verbose_name='Languages')),
                ('challenge_rating', models.IntegerField(blank=True, help_text='Monsters Challenge rating', max_length=200, null=True, verbose_name='Challenge Rating')),
                ('actions', models.JSONField(blank=True, null=True, verbose_name='Actions')),
                ('reactions', models.JSONField(blank=True, null=True, verbose_name='Reactions')),
                ('legendary_desc', models.CharField(blank=True, help_text='Monsters type', max_length=200, null=True, verbose_name='Type')),
                ('legendary_actions', models.JSONField(blank=True, null=True, verbose_name='Legendary Actions')),
                ('special_abilities', models.JSONField(blank=True, null=True, verbose_name='Special Abilities')),
            ],
            options={
                'verbose_name': 'Monster',
                'verbose_name_plural': 'Monsters',
            },
        ),
    ]
