# Generated by Django 4.1.5 on 2023-01-30 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0008_monster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='legendary_desc',
            field=models.TextField(blank=True, help_text='Monsters type', max_length=1000, null=True, verbose_name='Legendary Description'),
        ),
    ]
