# Generated by Django 4.1.5 on 2023-01-31 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0010_alter_monster_challenge_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='book_source',
            field=models.CharField(blank=True, help_text='What book is this monster from', max_length=200, null=True, verbose_name='Book Source'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='armor_class',
            field=models.IntegerField(blank=True, help_text='Monsters Armor Class', null=True, verbose_name='Armor Class'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='hit_points',
            field=models.IntegerField(blank=True, help_text='Monsters Hit points', null=True, verbose_name='Hit Points'),
        ),
    ]
