# Generated by Django 4.1.5 on 2023-01-31 15:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dnd', '0011_monster_book_source_alter_monster_armor_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
